dist: trusty
sudo: false
language: ruby
before_install: gem install bundler -v 1.14.6
rvm:
  - "2.6.1"
  - "2.5.3"
  - "2.4.4"
  - "2.3.8"
  - "2.2.9"
  - "2.1.10"
  - "2.0.0"
  - "1.9.3"
  - "ruby-head"
  - "jruby"
  - "jruby-19mode"
  - "jruby-head"

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
