dist: xenial
language: ruby

before_install:
  # Bundler 2.x does not work with older Rubies
  - bundle -v || gem install bundler -v "< 2"

rvm:
  - "3.0"
  - "2.7"
  - "2.6"
  - "2.5"
  - "2.4"
  - "2.3"
  - "2.2"
  - "2.1"
  - "2.0"
  - "1.9.3"
  - "ruby-head"
  - "jruby"
  - "jruby-19mode"
  - "jruby-head"

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
